# Autogenerated with `webdata` and `webtype_gen`

from typing import Literal, TypedDict



HTMLTag = Literal['html', 'head', 'title', 'base', 'link', 'meta', 'style', 'body', 'article', 'section', 'nav', 'aside', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'footer', 'address', 'p', 'hr', 'pre', 'blockquote', 'ol', 'ul', 'li', 'dl', 'dt', 'dd', 'figure', 'figcaption', 'main', 'div', 'a', 'em', 'strong', 'small', 's', 'cite', 'q', 'dfn', 'abbr', 'ruby', 'rb', 'rt', 'rp', 'time', 'code', 'var', 'samp', 'kbd', 'sub', 'sup', 'i', 'b', 'u', 'mark', 'bdi', 'bdo', 'span', 'br', 'wbr', 'ins', 'del', 'picture', 'img', 'iframe', 'embed', 'object', 'param', 'video', 'audio', 'source', 'track', 'map', 'area', 'table', 'caption', 'colgroup', 'col', 'tbody', 'thead', 'tfoot', 'tr', 'td', 'th', 'form', 'label', 'input', 'button', 'select', 'datalist', 'optgroup', 'option', 'textarea', 'output', 'progress', 'meter', 'fieldset', 'legend', 'details', 'summary', 'dialog', 'script', 'noscript', 'template', 'canvas', 'slot', 'data', 'hgroup', 'menu', 'search', 'fencedframe', 'selectedcontent']


class HTMLAttribute(TypedDict, total=False):
    manifest:str
    href:str
    target:Literal["_blank", "_parent", "_self", "_top", ] | str
    crossorigin:Literal["anonymous", "use-credentials", ] | str
    rel:str
    media:str
    hreflang:str
    type:Literal["1", "A", "I", "a", "button", "checkbox", "color", "date", "datetime", "datetime-local", "email", "file", "hidden", "i", "image", "month", "number", "password", "radio", "range", "reset", "search", "submit", "tel", "text", "time", "url", "week", ] | str
    sizes:str
    name:str
    http_equiv:str
    content:str
    charset:str
    nonce:str
    scoped:str
    onafterprint:str
    onbeforeprint:str
    onbeforeunload:str
    onhashchange:str
    onlanguagechange:str
    onmessage:str
    onoffline:str
    ononline:str
    onpagehide:str
    onpageshow:str
    onpopstate:str
    onstorage:str
    onunload:str
    cite:str
    reversed:str
    start:str
    value:str
    download:str
    ping:str
    datetime:str
    alt:str
    src:str
    srcset:str
    usemap:str
    ismap:str
    width:str
    height:str
    decoding:Literal["async", "auto", "sync", ] | str
    loading:Literal["eager", "lazy", ] | str
    fetchpriority:Literal["auto", "high", "low", ] | str
    referrerpolicy:Literal["no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url", ] | str
    srcdoc:str
    sandbox:Literal["allow-forms", "allow-modals", "allow-pointer-lock", "allow-popups", "allow-popups-to-escape-sandbox", "allow-same-origin", "allow-scripts", "allow-top-navigation", ] | str
    seamless:str
    allowfullscreen:str
    data:str
    typemustmatch:str
    form:str
    poster:str
    preload:Literal["auto", "metadata", "none", ] | str
    autoplay:str
    mediagroup:str
    loop:str
    muted:str
    controls:str
    default:str
    kind:Literal["captions", "chapters", "descriptions", "metadata", "subtitles", ] | str
    label:str
    srclang:str
    coords:str
    shape:Literal["circle", "default", "poly", "rect", ] | str
    border:str
    span:str
    colspan:str
    rowspan:str
    headers:str
    scope:Literal["col", "colgroup", "row", "rowgroup", ] | str
    sorted:str
    abbr:str
    accept_charset:str
    action:str
    autocomplete:Literal["additional-name", "address-level1", "address-level2", "address-level3", "address-level4", "address-line1", "address-line2", "address-line3", "bday", "bday-day", "bday-month", "bday-year", "billing", "cc-additional-name", "cc-csc", "cc-exp", "cc-exp-month", "cc-exp-year", "cc-family-name", "cc-given-name", "cc-name", "cc-number", "cc-type", "country", "country-name", "current-password", "email", "family-name", "fax", "given-name", "home", "honorific-prefix", "honorific-suffix", "impp", "language", "mobile", "name", "new-password", "nickname", "off", "on", "organization", "organization-title", "pager", "photo", "postal-code", "sex", "shipping", "street-address", "tel", "tel-area-code", "tel-country-code", "tel-extension", "tel-local", "tel-local-prefix", "tel-local-suffix", "tel-national", "transaction-amount", "transaction-currency", "url", "username", "work", ] | str
    enctype:Literal["application/x-www-form-urlencoded", "multipart/form-data", "text/plain", ] | str
    method:Literal["dialog", "get", "post", ] | str
    novalidate:str
    for_:str
    accept:str
    autofocus:str
    checked:str
    dirname:str
    disabled:str
    formaction:str
    formenctype:Literal["application/x-www-form-urlencoded", "multipart/form-data", "text/plain", ] | str
    formmethod:Literal["get", "post", ] | str
    formnovalidate:str
    formtarget:str
    inputmode:Literal["email", "full-width-latin", "kana", "kana-name", "katakana", "latin", "latin-name", "latin-prose", "numeric", "tel", "url", "verbatim", ] | str
    list:str
    max:str
    maxlength:str
    min:str
    minlength:str
    multiple:str
    pattern:str
    placeholder:str
    popovertarget:str
    popovertargetaction:str
    readonly:str
    required:str
    size:str
    step:str
    selected:str
    cols:str
    rows:str
    wrap:Literal["hard", "soft", ] | str
    low:str
    high:str
    optimum:str
    open:str
    async_:str
    defer:str
    allow:str
    accesskey:str
    autocapitalize:str
    autocorrect:Literal["off", "on", ] | str
    class_:str
    contenteditable:str
    contextmenu:str
    dir:Literal["auto", "ltr", "rtl", ] | str
    draggable:Literal["false", "true", ] | str
    dropzone:str
    enterkeyhint:Literal["done", "enter", "go", "next", "previous", "search", "send", ] | str
    exportparts:str
    hidden:str
    id:str
    inert:str
    is_:str
    itemid:str
    itemprop:str
    itemref:str
    itemscope:str
    itemtype:str
    lang:str
    part:str
    popover:Literal["auto", "hint", "manual", ] | str
    role:Literal["alert", "alertdialog", "application", "article", "banner", "button", "cell", "checkbox", "columnheader", "combobox", "complementary", "contentinfo", "definition", "dialog", "directory", "doc-abstract", "doc-acknowledgments", "doc-afterword", "doc-appendix", "doc-backlink", "doc-biblioentry", "doc-bibliography", "doc-biblioref", "doc-chapter", "doc-colophon", "doc-conclusion", "doc-cover", "doc-credit", "doc-credits", "doc-dedication", "doc-endnote", "doc-endnotes", "doc-epigraph", "doc-epilogue", "doc-errata", "doc-example", "doc-footnote", "doc-foreword", "doc-glossary", "doc-glossref", "doc-index", "doc-introduction", "doc-noteref", "doc-notice", "doc-pagebreak", "doc-pagelist", "doc-part", "doc-preface", "doc-prologue", "doc-pullquote", "doc-qna", "doc-subtitle", "doc-tip", "doc-toc", "document", "feed", "figure", "form", "grid", "gridcell", "group", "heading", "img", "link", "list", "listbox", "listitem", "log", "main", "marquee", "math", "menu", "menubar", "menuitem", "menuitemcheckbox", "menuitemradio", "navigation", "none", "note", "option", "presentation", "progressbar", "radio", "radiogroup", "region", "row", "rowgroup", "rowheader", "scrollbar", "search", "searchbox", "separator", "slider", "spinbutton", "status", "switch", "tab", "table", "tablist", "tabpanel", "term", "text", "textbox", "timer", "toolbar", "tooltip", "tree", "treegrid", "treeitem", ] | str
    slot:str
    spellcheck:Literal["false", "true", ] | str
    style:str
    tabindex:str
    title:str
    translate:Literal["no", "yes", ] | str
    virtualkeyboardpolicy:Literal["false", "true", ] | str
    onabort:str
    onanimationend:str
    onanimationiteration:str
    onanimationstart:str
    onappinstalled:str
    onaudioprocess:str
    onaudioend:str
    onaudiostart:str
    onbeginEvent:str
    onblocked:str
    onblur:str
    onboundary:str
    oncached:str
    oncanplay:str
    oncanplaythrough:str
    onchange:str
    onchargingchange:str
    onchargingtimechange:str
    onchecking:str
    onclick:str
    onclose:str
    oncomplete:str
    oncompositionend:str
    oncompositionstart:str
    oncompositionupdate:str
    oncontextmenu:str
    oncopy:str
    oncut:str
    ondblclick:str
    ondevicechange:str
    ondevicelight:str
    ondevicemotion:str
    ondeviceorientation:str
    ondeviceproximity:str
    ondischargingtimechange:str
    onDOMActivate:str
    onDOMAttributeNameChanged:str
    onDOMAttrModified:str
    onDOMCharacterDataModified:str
    onDOMContentLoaded:str
    onDOMElementNameChanged:str
    onDOMFocusIn:str
    onDOMFocusOut:str
    onDOMNodeInserted:str
    onDOMNodeInsertedIntoDocument:str
    onDOMNodeRemoved:str
    onDOMNodeRemovedFromDocument:str
    onDOMSubtreeModified:str
    ondownloading:str
    ondrag:str
    ondragend:str
    ondragenter:str
    ondragleave:str
    ondragover:str
    ondragstart:str
    ondrop:str
    ondurationchange:str
    onemptied:str
    onend:str
    onended:str
    onendEvent:str
    onerror:str
    onfocus:str
    onfocusin:str
    onfocusout:str
    onfullscreenchange:str
    onfullscreenerror:str
    ongamepadconnected:str
    ongamepaddisconnected:str
    ongotpointercapture:str
    onlostpointercapture:str
    oninput:str
    oninvalid:str
    onkeydown:str
    onkeypress:str
    onkeyup:str
    onlevelchange:str
    onload:str
    onloadeddata:str
    onloadedmetadata:str
    onloadend:str
    onloadstart:str
    onmark:str
    onmessageerror:str
    onmousedown:str
    onmouseenter:str
    onmouseleave:str
    onmousemove:str
    onmouseout:str
    onmouseover:str
    onmouseup:str
    onnomatch:str
    onnotificationclick:str
    onnoupdate:str
    onobsolete:str
    onopen:str
    onorientationchange:str
    onpaste:str
    onpause:str
    onpointercancel:str
    onpointerdown:str
    onpointerenter:str
    onpointerleave:str
    onpointerlockchange:str
    onpointerlockerror:str
    onpointermove:str
    onpointerout:str
    onpointerover:str
    onpointerup:str
    onplay:str
    onplaying:str
    onprogress:str
    onpush:str
    onpushsubscriptionchange:str
    onratechange:str
    onreadystatechange:str
    onrepeatEvent:str
    onreset:str
    onresize:str
    onresourcetimingbufferfull:str
    onresult:str
    onresume:str
    onscroll:str
    onseeked:str
    onseeking:str
    onselect:str
    onselectstart:str
    onselectionchange:str
    onshow:str
    onslotchange:str
    onsoundend:str
    onsoundstart:str
    onspeechend:str
    onspeechstart:str
    onstalled:str
    onstart:str
    onsubmit:str
    onsuccess:str
    onsuspend:str
    onSVGAbort:str
    onSVGError:str
    onSVGLoad:str
    onSVGResize:str
    onSVGScroll:str
    onSVGUnload:str
    onSVGZoom:str
    ontimeout:str
    ontimeupdate:str
    ontouchcancel:str
    ontouchend:str
    ontouchmove:str
    ontouchstart:str
    ontransitionend:str
    onupdateready:str
    onupgradeneeded:str
    onuserproximity:str
    onvoiceschanged:str
    onversionchange:str
    onvisibilitychange:str
    onvolumechange:str
    onwaiting:str
    onwheel:str
    onforminput:str
    onformchange:str
    onmousewheel:str


class CSSProperty(TypedDict, total=False):
    _moz_animation: Literal["time, enum, timing-function, identifier, number", "alternate", "alternate-reverse", "backwards", "both", "forwards", "infinite", "none", "normal", "reverse", ] | str
    _moz_animation_delay: Literal["time", ] | str
    _moz_animation_direction: Literal["enum", "alternate", "alternate-reverse", "normal", "reverse", ] | str
    _moz_animation_duration: Literal["time", ] | str
    _moz_animation_iteration_count: Literal["number, enum", ] | str
    _moz_animation_name: Literal["identifier, enum", ] | str
    _moz_animation_play_state: Literal["enum", "paused", "running", ] | str
    _moz_animation_timing_function: Literal["timing-function", ] | str
    _moz_appearance: Literal["enum", "button", "button-arrow-down", "button-arrow-next", "button-arrow-previous", "button-arrow-up", "button-bevel", "checkbox", "checkbox-container", "checkbox-label", "dialog", "groupbox", "listbox", "menuarrow", "menuimage", "menuitem", "menuitemtext", "menulist", "menulist-button", "menulist-text", "menulist-textfield", "menupopup", "menuradio", "menuseparator", "-moz-mac-unified-toolbar", "-moz-win-borderless-glass", "-moz-win-browsertabbar-toolbox", "-moz-win-communications-toolbox", "-moz-win-glass", "-moz-win-media-toolbox", "none", "progressbar", "progresschunk", "radio", "radio-container", "radio-label", "radiomenuitem", "resizer", "resizerpanel", "scrollbarbutton-down", "scrollbarbutton-left", "scrollbarbutton-right", "scrollbarbutton-up", "scrollbar-small", "scrollbartrack-horizontal", "scrollbartrack-vertical", "separator", "spinner", "spinner-downbutton", "spinner-textfield", "spinner-upbutton", "statusbar", "statusbarpanel", "tab", "tabpanels", "tab-scroll-arrow-back", "tab-scroll-arrow-forward", "textfield", "textfield-multiline", "toolbar", "toolbox", "tooltip", "treeheadercell", "treeheadersortarrow", "treeitem", "treetwistyopen", "treeview", "treewisty", "window", ] | str
    _moz_backface_visibility: Literal["enum", "hidden", "visible", ] | str
    _moz_background_clip: Literal["box, enum", ] | str
    _moz_background_inline_policy: Literal["enum", "bounding-box", "continuous", "each-box", ] | str
    _moz_background_origin: Literal["box", ] | str
    _moz_border_bottom_colors: Literal["color", ] | str
    _moz_border_image: Literal["length, percentage, number, url, enum", "auto", "fill", "none", "repeat", "round", "space", "stretch", "url()", ] | str
    _moz_border_left_colors: Literal["color", ] | str
    _moz_border_right_colors: Literal["color", ] | str
    _moz_border_top_colors: Literal["color", ] | str
    _moz_box_align: Literal["enum", "baseline", "center", "end", "start", "stretch", ] | str
    _moz_box_direction: Literal["enum", "normal", "reverse", ] | str
    _moz_box_flex: Literal["number", ] | str
    _moz_box_flexgroup: Literal["integer", ] | str
    _moz_box_ordinal_group: Literal["integer", ] | str
    _moz_box_orient: Literal["enum", "block-axis", "horizontal", "inline-axis", "vertical", ] | str
    _moz_box_pack: Literal["enum", "center", "end", "justify", "start", ] | str
    _moz_box_sizing: Literal["enum", "border-box", "content-box", "padding-box", ] | str
    _moz_column_count: Literal["integer", ] | str
    _moz_column_gap: Literal["length", ] | str
    _moz_column_rule: Literal["length, line-width, line-style, color", ] | str
    _moz_column_rule_color: Literal["color", ] | str
    _moz_column_rule_style: Literal["line-style", ] | str
    _moz_column_rule_width: Literal["length, line-width", ] | str
    _moz_column_width: Literal["length", ] | str
    _moz_columns: Literal["length, integer", ] | str
    _moz_font_feature_settings: Literal["string, integer", ] | str
    _moz_hyphens: Literal["enum", "auto", "manual", "none", ] | str
    _moz_perspective: Literal["length", ] | str
    _moz_perspective_origin: Literal["position, percentage, length", ] | str
    _moz_text_align_last: Literal["enum", "auto", "center", "end", "justify", "left", "right", "start", ] | str
    _moz_text_decoration_color: Literal["color", ] | str
    _moz_text_decoration_line: Literal["enum", "line-through", "none", "overline", "underline", ] | str
    _moz_text_decoration_style: Literal["enum", "dashed", "dotted", "double", "none", "solid", "wavy", ] | str
    _moz_text_size_adjust: Literal["enum, percentage", "auto", "none", ] | str
    _moz_transform: Literal["enum", "matrix()", "matrix3d()", "none", "perspective", "rotate()", "rotate3d()", "rotateX('angle')", "rotateY('angle')", "rotateZ('angle')", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skew()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()", ] | str
    _moz_transform_origin: Literal["position, length, percentage", ] | str
    _moz_transition: Literal["time, property, timing-function, enum", "all", "none", ] | str
    _moz_transition_delay: Literal["time", ] | str
    _moz_transition_duration: Literal["time", ] | str
    _moz_transition_property: Literal["property", ] | str
    _moz_transition_timing_function: Literal["timing-function", ] | str
    _moz_user_focus: str
    _moz_user_select: Literal["enum", "all", "element", "elements", "-moz-all", "-moz-none", "none", "text", "toggle", ] | str
    _ms_accelerator: Literal["enum", "false", "true", ] | str
    _ms_behavior: Literal["url", ] | str
    _ms_block_progression: Literal["enum", "bt", "lr", "rl", "tb", ] | str
    _ms_content_zoom_chaining: str
    _ms_content_zoom_limit: Literal["percentage", ] | str
    _ms_content_zoom_limit_max: Literal["percentage", ] | str
    _ms_content_zoom_limit_min: Literal["percentage", ] | str
    _ms_content_zoom_snap: str
    _ms_content_zoom_snap_points: str
    _ms_content_zoom_snap_type: Literal["enum", "mandatory", "none", "proximity", ] | str
    _ms_content_zooming: Literal["enum", "none", "zoom", ] | str
    _ms_filter: Literal["string", ] | str
    _ms_flex: Literal["length, number, percentage", ] | str
    _ms_flex_align: Literal["enum", "baseline", "center", "end", "start", "stretch", ] | str
    _ms_flex_direction: Literal["enum", "column", "column-reverse", "row", "row-reverse", ] | str
    _ms_flex_flow: Literal["enum", "column", "column-reverse", "nowrap", "row", "wrap", "wrap-reverse", ] | str
    _ms_flex_item_align: Literal["enum", "auto", "baseline", "center", "end", "start", "stretch", ] | str
    _ms_flex_line_pack: Literal["enum", "center", "distribute", "end", "justify", "start", "stretch", ] | str
    _ms_flex_order: Literal["integer", ] | str
    _ms_flex_pack: Literal["enum", "center", "distribute", "end", "justify", "start", ] | str
    _ms_flex_wrap: Literal["enum", "nowrap", "wrap", "wrap-reverse", ] | str
    _ms_flow_from: Literal["identifier", ] | str
    _ms_flow_into: Literal["identifier", ] | str
    _ms_grid_column: Literal["integer, string, enum", "auto", "end", "start", ] | str
    _ms_grid_column_align: Literal["enum", "center", "end", "start", "stretch", ] | str
    _ms_grid_column_span: Literal["integer", ] | str
    _ms_grid_columns: str
    _ms_grid_layer: Literal["integer", ] | str
    _ms_grid_row: Literal["integer, string, enum", "auto", "end", "start", ] | str
    _ms_grid_row_align: Literal["enum", "center", "end", "start", "stretch", ] | str
    _ms_grid_row_span: Literal["integer", ] | str
    _ms_grid_rows: str
    _ms_high_contrast_adjust: Literal["enum", "auto", "none", ] | str
    _ms_hyphenate_limit_chars: Literal["integer", ] | str
    _ms_hyphenate_limit_lines: Literal["integer", ] | str
    _ms_hyphenate_limit_zone: Literal["percentage, length", ] | str
    _ms_hyphens: Literal["enum", "auto", "manual", "none", ] | str
    _ms_ime_mode: Literal["enum", "active", "auto", "disabled", "inactive", "normal", ] | str
    _ms_interpolation_mode: Literal["enum", "bicubic", "nearest-neighbor", ] | str
    _ms_layout_grid: str
    _ms_layout_grid_char: Literal["enum, length, percentage", "auto", "none", ] | str
    _ms_layout_grid_line: Literal["length", ] | str
    _ms_layout_grid_mode: Literal["enum", "both", "char", "line", "none", ] | str
    _ms_layout_grid_type: Literal["enum", "fixed", "loose", "strict", ] | str
    _ms_line_break: Literal["enum", "auto", "keep-all", "newspaper", "normal", "strict", ] | str
    _ms_overflow_style: Literal["enum", "auto", "-ms-autohiding-scrollbar", "none", "scrollbar", ] | str
    _ms_perspective: Literal["length", ] | str
    _ms_perspective_origin: Literal["position, percentage, length", ] | str
    _ms_perspective_origin_x: Literal["position, percentage, length", ] | str
    _ms_perspective_origin_y: Literal["position, percentage, length", ] | str
    _ms_progress_appearance: Literal["enum", "bar", "ring", ] | str
    _ms_scroll_chaining: Literal["enum, length", "chained", "none", ] | str
    _ms_scroll_limit: Literal["length", ] | str
    _ms_scroll_limit_x_max: Literal["length", ] | str
    _ms_scroll_limit_x_min: Literal["length", ] | str
    _ms_scroll_limit_y_max: Literal["length", ] | str
    _ms_scroll_limit_y_min: Literal["length", ] | str
    _ms_scroll_rails: Literal["enum, length", "none", "railed", ] | str
    _ms_scroll_snap_points_x: Literal["enum", "snapInterval(100%, 100%)", "snapList()", ] | str
    _ms_scroll_snap_points_y: Literal["enum", "snapInterval(100%, 100%)", "snapList()", ] | str
    _ms_scroll_snap_type: Literal["enum", "none", "mandatory", "proximity", ] | str
    _ms_scroll_snap_x: Literal["enum", "mandatory", "none", "proximity", "snapInterval(100%, 100%)", "snapList()", ] | str
    _ms_scroll_snap_y: Literal["enum", "mandatory", "none", "proximity", "snapInterval(100%, 100%)", "snapList()", ] | str
    _ms_scroll_translation: Literal["enum", "none", "vertical-to-horizontal", ] | str
    _ms_scrollbar_3dlight_color: Literal["color", ] | str
    _ms_scrollbar_arrow_color: Literal["color", ] | str
    _ms_scrollbar_base_color: Literal["color", ] | str
    _ms_scrollbar_darkshadow_color: Literal["color", ] | str
    _ms_scrollbar_face_color: Literal["color", ] | str
    _ms_scrollbar_highlight_color: Literal["color", ] | str
    _ms_scrollbar_shadow_color: Literal["color", ] | str
    _ms_scrollbar_track_color: Literal["color", ] | str
    _ms_text_align_last: Literal["enum", "auto", "center", "end", "justify", "left", "right", "start", ] | str
    _ms_text_autospace: Literal["enum", "ideograph-alpha", "ideograph-numeric", "ideograph-parenthesis", "ideograph-space", "none", "punctuation", ] | str
    _ms_text_combine_horizontal: Literal["enum, integer", "all", "digits", "none", ] | str
    _ms_text_justify: Literal["enum", "auto", "distribute", "inter-cluster", "inter-ideograph", "inter-word", "kashida", "none", "trim", ] | str
    _ms_text_kashida_space: Literal["percentage", ] | str
    _ms_text_overflow: Literal["enum", "clip", "ellipsis", ] | str
    _ms_text_size_adjust: Literal["enum, percentage", "auto", "none", ] | str
    _ms_text_underline_position: Literal["enum", "alphabetic", "auto", "over", "under", ] | str
    _ms_touch_action: Literal["enum", "auto", "double-tap-zoom", "manipulation", "none", "pan-x", "pan-y", "pinch-zoom", ] | str
    _ms_touch_select: Literal["enum", "grippers", "none", ] | str
    _ms_transform: Literal["enum", "matrix()", "matrix3d()", "none", "rotate()", "rotate3d()", "rotateX('angle')", "rotateY('angle')", "rotateZ('angle')", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skew()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()", ] | str
    _ms_transform_origin: Literal["position, length, percentage", ] | str
    _ms_transform_origin_x: Literal["length, percentage", ] | str
    _ms_transform_origin_y: Literal["length, percentage", ] | str
    _ms_transform_origin_z: Literal["length, percentage", ] | str
    _ms_user_select: Literal["enum", "element", "none", "text", ] | str
    _ms_word_break: Literal["enum", "break-all", "keep-all", "normal", ] | str
    _ms_word_wrap: Literal["enum", "break-word", "hyphenate", "normal", ] | str
    _ms_wrap_flow: Literal["enum", "auto", "both", "clear", "end", "maximum", "minimum", "start", ] | str
    _ms_wrap_margin: Literal["length, percentage", ] | str
    _ms_wrap_through: Literal["enum", "none", "wrap", ] | str
    _ms_writing_mode: Literal["enum", "bt-lr", "bt-rl", "lr-bt", "lr-tb", "rl-bt", "rl-tb", "tb-lr", "tb-rl", ] | str
    _ms_zoom: Literal["enum, integer, number, percentage", ] | str
    _ms_zoom_animation: Literal["enum", "default", "none", ] | str
    _o_animation: Literal["time, enum, timing-function, identifier, number", "alternate", "alternate-reverse", "backwards", "both", "forwards", "infinite", "none", "normal", "reverse", ] | str
    _o_animation_delay: Literal["time", ] | str
    _o_animation_direction: Literal["enum", "alternate", "alternate-reverse", "normal", "reverse", ] | str
    _o_animation_duration: Literal["time", ] | str
    _o_animation_fill_mode: Literal["enum", "backwards", "both", "forwards", "none", ] | str
    _o_animation_iteration_count: Literal["number, enum", ] | str
    _o_animation_name: Literal["identifier, enum", ] | str
    _o_animation_play_state: Literal["enum", "paused", "running", ] | str
    _o_animation_timing_function: Literal["timing-function", ] | str
    _o_border_image: Literal["length, percentage, number, image, enum", "auto", "fill", "none", "repeat", "round", "space", "stretch", ] | str
    _o_object_fit: Literal["enum", "contain", "cover", "fill", "none", "scale-down", ] | str
    _o_object_position: Literal["position, length, percentage", ] | str
    _o_tab_size: Literal["integer, length", ] | str
    _o_table_baseline: Literal["integer", ] | str
    _o_text_overflow: Literal["enum", "clip", "ellipsis", ] | str
    _o_transform: Literal["enum", "matrix()", "matrix3d()", "none", "rotate()", "rotate3d()", "rotateX('angle')", "rotateY('angle')", "rotateZ('angle')", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skew()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()", ] | str
    _o_transform_origin: Literal["positon, length, percentage", ] | str
    _o_transition: Literal["time, property, timing-function, enum", "all", "none", ] | str
    _o_transition_delay: Literal["time", ] | str
    _o_transition_duration: Literal["time", ] | str
    _o_transition_property: Literal["property", ] | str
    _o_transition_timing_function: Literal["timing-function", ] | str
    _webkit_animation: Literal["time, enum, timing-function, identifier, number", "alternate", "alternate-reverse", "backwards", "both", "forwards", "infinite", "none", "normal", "reverse", ] | str
    _webkit_animation_delay: Literal["time", ] | str
    _webkit_animation_direction: Literal["enum", "alternate", "alternate-reverse", "normal", "reverse", ] | str
    _webkit_animation_duration: Literal["time", ] | str
    _webkit_animation_fill_mode: Literal["enum", "backwards", "both", "forwards", "none", ] | str
    _webkit_animation_iteration_count: Literal["number, enum", ] | str
    _webkit_animation_name: Literal["identifier, enum", ] | str
    _webkit_animation_play_state: Literal["enum", "paused", "running", ] | str
    _webkit_animation_timing_function: Literal["timing-function", ] | str
    _webkit_appearance: Literal["enum", "button", "button-bevel", "caps-lock-indicator", "caret", "checkbox", "default-button", "listbox", "listitem", "media-fullscreen-button", "media-mute-button", "media-play-button", "media-seek-back-button", "media-seek-forward-button", "media-slider", "media-sliderthumb", "menulist", "menulist-button", "menulist-text", "menulist-textfield", "none", "push-button", "radio", "scrollbarbutton-down", "scrollbarbutton-left", "scrollbarbutton-right", "scrollbarbutton-up", "scrollbargripper-horizontal", "scrollbargripper-vertical", "scrollbarthumb-horizontal", "scrollbarthumb-vertical", "scrollbartrack-horizontal", "scrollbartrack-vertical", "searchfield", "searchfield-cancel-button", "searchfield-decoration", "searchfield-results-button", "searchfield-results-decoration", "slider-horizontal", "sliderthumb-horizontal", "sliderthumb-vertical", "slider-vertical", "square-button", "textarea", "textfield", ] | str
    _webkit_backdrop_filter: Literal["enum, url", "none", "blur()", "brightness()", "contrast()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "opacity()", "saturate()", "sepia()", "url()", ] | str
    _webkit_backface_visibility: Literal["enum", "hidden", "visible", ] | str
    _webkit_background_clip: Literal["box", ] | str
    _webkit_background_composite: Literal["enum", "border", "padding", ] | str
    _webkit_background_origin: Literal["box", ] | str
    _webkit_border_image: Literal["length, percentage, number, url, enum", "auto", "fill", "none", "repeat", "round", "space", "stretch", "url()", ] | str
    _webkit_box_align: Literal["enum", "baseline", "center", "end", "start", "stretch", ] | str
    _webkit_box_direction: Literal["enum", "normal", "reverse", ] | str
    _webkit_box_flex: Literal["number", ] | str
    _webkit_box_flex_group: Literal["integer", ] | str
    _webkit_box_ordinal_group: Literal["integer", ] | str
    _webkit_box_orient: Literal["enum", "block-axis", "horizontal", "inline-axis", "vertical", ] | str
    _webkit_box_pack: Literal["enum", "center", "end", "justify", "start", ] | str
    _webkit_box_reflect: str
    _webkit_box_sizing: Literal["enum", "border-box", "content-box", ] | str
    _webkit_break_after: Literal["enum", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right", ] | str
    _webkit_break_before: Literal["enum", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right", ] | str
    _webkit_break_inside: Literal["enum", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", ] | str
    _webkit_column_break_after: Literal["enum", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right", ] | str
    _webkit_column_break_before: Literal["enum", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right", ] | str
    _webkit_column_break_inside: Literal["enum", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", ] | str
    _webkit_column_count: Literal["integer", ] | str
    _webkit_column_gap: Literal["length", ] | str
    _webkit_column_rule: Literal["length, line-width, line-style, color", ] | str
    _webkit_column_rule_color: Literal["color", ] | str
    _webkit_column_rule_style: Literal["line-style", ] | str
    _webkit_column_rule_width: Literal["length, line-width", ] | str
    _webkit_column_span: Literal["enum", "all", "none", ] | str
    _webkit_column_width: Literal["length", ] | str
    _webkit_columns: Literal["length, integer", ] | str
    _webkit_filter: Literal["enum, url", "none", "blur()", "brightness()", "contrast()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "opacity()", "saturate()", "sepia()", "url()", ] | str
    _webkit_flow_from: Literal["identifier", ] | str
    _webkit_flow_into: Literal["identifier", ] | str
    _webkit_font_feature_settings: Literal["string, integer", ] | str
    _webkit_hyphens: Literal["enum", "auto", "manual", "none", ] | str
    _webkit_line_break: str
    _webkit_margin_bottom_collapse: Literal["enum", "collapse", "discard", "separate", ] | str
    _webkit_margin_collapse: Literal["enum", "collapse", "discard", "separate", ] | str
    _webkit_margin_start: Literal["percentage, length", ] | str
    _webkit_margin_top_collapse: Literal["enum", "collapse", "discard", "separate", ] | str
    _webkit_mask_clip: Literal["box", ] | str
    _webkit_mask_image: Literal["url, image, enum", "none", "url()", ] | str
    _webkit_mask_origin: Literal["box", ] | str
    _webkit_mask_repeat: Literal["repeat", ] | str
    _webkit_mask_size: Literal["length, percentage, enum", "auto", "contain", "cover", ] | str
    _webkit_nbsp_mode: str
    _webkit_overflow_scrolling: str
    _webkit_padding_start: Literal["percentage, length", ] | str
    _webkit_perspective: Literal["length", ] | str
    _webkit_perspective_origin: Literal["position, percentage, length", ] | str
    _webkit_region_fragment: Literal["enum", "auto", "break", ] | str
    _webkit_tap_highlight_color: Literal["color", ] | str
    _webkit_text_fill_color: Literal["color", ] | str
    _webkit_text_size_adjust: Literal["percentage", ] | str
    _webkit_text_stroke: Literal["length, line-width, color, percentage", ] | str
    _webkit_text_stroke_color: Literal["color", ] | str
    _webkit_text_stroke_width: Literal["length, line-width, percentage", ] | str
    _webkit_touch_callout: Literal["enum", ] | str
    _webkit_transform: Literal["enum", "matrix()", "matrix3d()", "none", "perspective()", "rotate()", "rotate3d()", "rotateX('angle')", "rotateY('angle')", "rotateZ('angle')", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skew()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()", ] | str
    _webkit_transform_origin: Literal["position, length, percentage", ] | str
    _webkit_transform_origin_x: Literal["length, percentage", ] | str
    _webkit_transform_origin_y: Literal["length, percentage", ] | str
    _webkit_transform_origin_z: Literal["length, percentage", ] | str
    _webkit_transform_style: Literal["enum", "flat", "preserve-3d", ] | str
    _webkit_transition: Literal["time, property, timing-function, enum", "all", "none", ] | str
    _webkit_transition_delay: Literal["time", ] | str
    _webkit_transition_duration: Literal["time", ] | str
    _webkit_transition_property: Literal["property", ] | str
    _webkit_transition_timing_function: Literal["timing-function", ] | str
    _webkit_user_drag: Literal["enum", "auto", "element", "none", ] | str
    _webkit_user_modify: Literal["enum", "read-only", "read-write", "read-write-plaintext-only", ] | str
    _webkit_user_select: Literal["enum", "auto", "none", "text", ] | str
    additive_symbols: Literal["integer, string, image, identifier", ] | str
    align_content: Literal["enum", "center", "flex-end", "flex-start", "space-around", "space-between", "stretch", "start", "end", "normal", "baseline", "first baseline", "last baseline", "space-around", "space-between", "space-evenly", "stretch", "safe", "unsafe", ] | str
    align_items: Literal["enum", "baseline", "center", "flex-end", "flex-start", "stretch", "normal", "start", "end", "self-start", "self-end", "first baseline", "last baseline", "stretch", "safe", "unsafe", ] | str
    align_self: Literal["enum", "auto", "normal", "self-end", "self-start", "baseline", "center", "flex-end", "flex-start", "stretch", "baseline", "first baseline", "last baseline", "safe", "unsafe", ] | str
    alignment_baseline: Literal["enum", "alphabetic", "baseline", "bottom", "center", "central", "mathematical", "middle", "text-bottom", "text-top", "top", ] | str
    all: Literal["enum", ] | str
    alt: Literal["string, enum", ] | str
    animation: Literal["time, timing-function, enum, identifier, number", "alternate", "alternate-reverse", "backwards", "both", "forwards", "infinite", "none", "normal", "reverse", ] | str
    animation_composition: Literal["enum", "accumulate", "add", "replace", ] | str
    animation_delay: Literal["time", ] | str
    animation_direction: Literal["enum", "alternate", "alternate-reverse", "normal", "reverse", ] | str
    animation_duration: Literal["time", ] | str
    animation_fill_mode: Literal["enum", "backwards", "both", "forwards", "none", ] | str
    animation_iteration_count: Literal["number, enum", ] | str
    animation_name: Literal["identifier, enum", ] | str
    animation_play_state: Literal["enum", "paused", "running", ] | str
    animation_timing_function: Literal["timing-function", ] | str
    backdrop_filter: Literal["enum, url", "none", "blur()", "brightness()", "contrast()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "opacity()", "saturate()", "sepia()", "url()", ] | str
    backface_visibility: Literal["enum", "hidden", "visible", ] | str
    background: Literal["enum, image, color, position, length, repeat, percentage, box", "fixed", "local", "none", "scroll", ] | str
    background_attachment: Literal["enum", "fixed", "local", "scroll", ] | str
    background_blend_mode: Literal["enum", "normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "color-burn", "hard-light", "soft-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity", ] | str
    background_clip: Literal["box", ] | str
    background_color: Literal["color", ] | str
    background_image: Literal["image, enum", ] | str
    background_image_transform: Literal["enum", "logical", "physical", "rotate", ] | str
    background_origin: Literal["box", ] | str
    background_position: Literal["position, length, percentage", ] | str
    background_position_x: Literal["length, percentage", ] | str
    background_position_y: Literal["length, percentage", ] | str
    background_repeat: Literal["repeat", ] | str
    background_size: Literal["length, percentage", ] | str
    baseline_shift: Literal["length, percentage, enum", "sub", "super", ] | str
    behavior: Literal["url", ] | str
    block_size: Literal["length, percentage", ] | str
    border: Literal["length, line-width, line-style, color", ] | str
    border_block_end: Literal["length, line-width, line-style, color", ] | str
    border_block_end_color: Literal["color", ] | str
    border_block_end_style: Literal["line-style", ] | str
    border_block_end_width: Literal["length, line-width", ] | str
    border_block_start: Literal["length, line-width, line-style, color", ] | str
    border_block_start_color: Literal["color", ] | str
    border_block_start_style: Literal["line-style", ] | str
    border_block_start_width: Literal["length, line-width", ] | str
    border_bottom: Literal["length, line-width, line-style, color", ] | str
    border_bottom_color: Literal["color", ] | str
    border_bottom_left_radius: Literal["length, percentage", ] | str
    border_bottom_right_radius: Literal["length, percentage", ] | str
    border_bottom_style: Literal["line-style", ] | str
    border_bottom_width: Literal["length, line-width", ] | str
    border_collapse: Literal["enum", "collapse", "separate", ] | str
    border_color: Literal["color", ] | str
    border_image: Literal["length, percentage, number, url, enum", "auto", "fill", "none", "repeat", "round", "space", "stretch", "url()", ] | str
    border_image_outset: Literal["length, number", ] | str
    border_image_repeat: Literal["enum", "repeat", "round", "space", "stretch", ] | str
    border_image_slice: Literal["number, percentage", ] | str
    border_image_source: Literal["image", ] | str
    border_image_transform: Literal["enum", "logical", "physical", "rotate", ] | str
    border_image_width: Literal["length, percentage, number", ] | str
    border_inline_end: Literal["length, line-width, line-style, color", ] | str
    border_inline_end_color: Literal["color", ] | str
    border_inline_end_style: Literal["line-style", ] | str
    border_inline_end_width: Literal["length, line-width", ] | str
    border_inline_start: Literal["length, line-width, line-style, color", ] | str
    border_inline_start_color: Literal["color", ] | str
    border_inline_start_style: Literal["line-style", ] | str
    border_inline_start_width: Literal["length, line-width", ] | str
    border_left: Literal["length, line-width, line-style, color", ] | str
    border_left_color: Literal["color", ] | str
    border_left_style: Literal["line-style", ] | str
    border_left_width: Literal["length, line-width", ] | str
    border_radius: Literal["length, percentage", ] | str
    border_right: Literal["length, line-width, line-style, color", ] | str
    border_right_color: Literal["color", ] | str
    border_right_style: Literal["line-style", ] | str
    border_right_width: Literal["length, line-width", ] | str
    border_spacing: Literal["length", ] | str
    border_style: Literal["line-style", ] | str
    border_top: Literal["length, line-width, line-style, color", ] | str
    border_top_color: Literal["color", ] | str
    border_top_left_radius: Literal["length, percentage", ] | str
    border_top_right_radius: Literal["length, percentage", ] | str
    border_top_style: Literal["line-style", ] | str
    border_top_width: Literal["length, line-width", ] | str
    border_width: Literal["length, line-width", ] | str
    bottom: Literal["length, percentage", ] | str
    box_decoration_break: Literal["enum", "clone", "slice", ] | str
    box_shadow: Literal["length, color, enum", "inset", "none", ] | str
    box_sizing: Literal["enum", "border-box", "content-box", ] | str
    box_snap: Literal["enum", "none", "block-start", "block-end", "center", "baseline", "last-baseline", ] | str
    box_suppress: Literal["enum", "show", "discard", "hide", ] | str
    break_after: Literal["enum", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right", "recto", "verso", ] | str
    break_before: Literal["enum", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right", "recto", "verso", ] | str
    break_inside: Literal["enum", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", ] | str
    caption_side: Literal["enum", "block-end", "block-start", "bottom", "inline-end", "inline-start", "top", ] | str
    caret_color: Literal["color, enum", ] | str
    clear: Literal["enum", "both", "inline-end", "inline-start", "left", "none", "right", ] | str
    clip: Literal["enum", "auto", "rect()", ] | str
    clip_path: Literal["url, shape, geometry-box, enum", "none", "url()", ] | str
    clip_rule: Literal["enum", "evenodd", "nonzero", ] | str
    color: Literal["color", ] | str
    color_adjust: Literal["enum", "economy", "exact", ] | str
    color_interpolation: Literal["enum", "auto", "linearRGB", "sRGB", ] | str
    color_interpolation_filters: Literal["enum", "auto", "linearRGB", "sRGB", ] | str
    color_rendering: Literal["enum", "auto", "optimizeQuality", "optimizeSpeed", ] | str
    column_count: Literal["integer, enum", ] | str
    column_fill: Literal["enum", "auto", "balance", ] | str
    column_gap: Literal["length, enum", ] | str
    column_rule: Literal["length, line-width, line-style, color", ] | str
    column_rule_color: Literal["color", ] | str
    column_rule_style: Literal["line-style", ] | str
    column_rule_width: Literal["length, line-width", ] | str
    column_span: Literal["enum", "all", "none", ] | str
    column_width: Literal["length, enum", "auto", "fill", "fit-content", "max-content", "min-content", ] | str
    columns: Literal["length, integer, enum", ] | str
    contain: Literal["enum", "none", "strict", "content", "size", "layout", "style", "paint", ] | str
    content: Literal["string, url", ] | str
    counter_increment: Literal["identifier, integer", ] | str
    counter_reset: Literal["identifier, integer", ] | str
    crop: Literal["enum", "auto", "insert-rect(top, right, bottom, left)", "rect(top, right, bottom, left)", ] | str
    cue: Literal["url, volume, enum", "none", "url()", ] | str
    cue_after: Literal["url, volume, enum", "none", "url()", ] | str
    cue_before: Literal["url, volume, enum", "none", "url()", ] | str
    cursor: Literal["url, number, enum", "alias", "all-scroll", "auto", "cell", "col-resize", "context-menu", "copy", "crosshair", "default", "e-resize", "ew-resize", "grab", "grabbing", "help", "move", "-moz-grab", "-moz-grabbing", "-moz-zoom-in", "-moz-zoom-out", "ne-resize", "nesw-resize", "no-drop", "none", "not-allowed", "n-resize", "ns-resize", "nw-resize", "nwse-resize", "pointer", "progress", "row-resize", "se-resize", "s-resize", "sw-resize", "text", "vertical-text", "wait", "-webkit-grab", "-webkit-grabbing", "-webkit-zoom-in", "-webkit-zoom-out", "w-resize", "zoom-in", "zoom-out", ] | str
    cx: Literal["length, percentage", ] | str
    cy: Literal["length, percentage", ] | str
    direction: Literal["enum", "ltr", "rtl", ] | str
    display: Literal["enum", "block", "contents", "flex", "flexbox", "flow", "flow-root", "grid", "inline", "inline-block", "inline-flex", "inline-flexbox", "inline-grid", "inline-table", "list-item", "-moz-box", "-moz-deck", "-moz-grid", "-moz-grid-group", "-moz-grid-line", "-moz-groupbox", "-moz-inline-box", "-moz-inline-grid", "-moz-inline-stack", "-moz-marker", "-moz-popup", "-moz-stack", "-ms-flexbox", "-ms-grid", "-ms-inline-flexbox", "-ms-inline-grid", "none", "ruby", "ruby-base", "ruby-base-container", "ruby-base-group", "ruby-text", "ruby-text-container", "ruby-text-group", "run-in", "table", "table-caption", "table-cell", "table-column", "table-column-group", "table-footer-group", "table-header-group", "table-row", "table-row-group", "-webkit-box", "-webkit-flex", "-webkit-inline-box", "-webkit-inline-flex", ] | str
    dominant_baseline: Literal["enum", "auto", "text-bottom", "alphabetic", "central", "mathematical", "hanging", "text-top", ] | str
    empty_cells: Literal["enum", "hide", "-moz-show-background", "show", ] | str
    enable_background: Literal["integer, length, percentage, enum", "accumulate", "new", ] | str
    fallback: Literal["identifier", ] | str
    fill: Literal["color, enum, url", "child", "child()", "context-fill", "context-stroke", "url()", "none", ] | str
    fill_opacity: Literal["number(0-1)", ] | str
    fill_rule: Literal["enum", "evenodd", "nonzero", ] | str
    filter: Literal["enum, url", "none", "blur()", "brightness()", "contrast()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "opacity()", "saturate()", "sepia()", "url()", ] | str
    flex: Literal["length, number, percentage", ] | str
    flex_basis: Literal["length, number, percentage", ] | str
    flex_direction: Literal["enum", "column", "column-reverse", "row", "row-reverse", ] | str
    flex_flow: Literal["enum", "column", "column-reverse", "nowrap", "row", "row-reverse", "wrap", "wrap-reverse", ] | str
    flex_grow: Literal["number", ] | str
    flex_shrink: Literal["number", ] | str
    flex_wrap: Literal["enum", "nowrap", "wrap", "wrap-reverse", ] | str
    float: Literal["enum", "inline-end", "inline-start", "left", "none", "right", ] | str
    flood_color: Literal["color", ] | str
    flood_opacity: Literal["number(0-1), percentage", ] | str
    flow_from: Literal["identifier", ] | str
    flow_into: Literal["identifier", ] | str
    font: Literal["font", ] | str
    font_family: Literal["font", ] | str
    font_feature_settings: Literal["string, integer", ] | str
    font_kerning: Literal["enum", "auto", "none", "normal", ] | str
    font_language_override: Literal["string", ] | str
    font_size: Literal["length, percentage", ] | str
    font_size_adjust: Literal["number", ] | str
    font_stretch: Literal["enum", "condensed", "expanded", "extra-condensed", "extra-expanded", "narrower", "normal", "semi-condensed", "semi-expanded", "ultra-condensed", "ultra-expanded", "wider", ] | str
    font_style: Literal["enum", "italic", "normal", "oblique", ] | str
    font_synthesis: Literal["enum", "none", "style", "weight", ] | str
    font_variant: Literal["enum", "normal", "small-caps", ] | str
    font_variant_alternates: Literal["enum", "annotation()", "character-variant()", "historical-forms", "normal", "ornaments()", "styleset()", "stylistic()", "swash()", ] | str
    font_variant_caps: Literal["enum", "all-petite-caps", "all-small-caps", "normal", "petite-caps", "small-caps", "titling-caps", "unicase", ] | str
    font_variant_east_asian: Literal["enum", "full-width", "jis04", "jis78", "jis83", "jis90", "normal", "proportional-width", "ruby", "simplified", "traditional", ] | str
    font_variant_ligatures: Literal["enum", "additional-ligatures", "common-ligatures", "contextual", "discretionary-ligatures", "historical-ligatures", "no-additional-ligatures", "no-common-ligatures", "no-contextual", "no-discretionary-ligatures", "no-historical-ligatures", "none", "normal", ] | str
    font_variant_numeric: Literal["enum", "diagonal-fractions", "lining-nums", "normal", "oldstyle-nums", "ordinal", "proportional-nums", "slashed-zero", "stacked-fractions", "tabular-nums", ] | str
    font_variant_position: Literal["enum", "normal", "sub", "super", ] | str
    font_weight: Literal["enum", "100", "200", "300", "400", "500", "600", "700", "800", "900", "bold", "bolder", "lighter", "normal", ] | str
    glyph_orientation_horizontal: Literal["angle, number", ] | str
    glyph_orientation_vertical: Literal["angle, number, enum", ] | str
    grid: Literal["identifier, length, percentage, string, enum", ] | str
    grid_area: Literal["identifier, integer", ] | str
    grid_auto_columns: Literal["length, percentage", ] | str
    grid_auto_flow: Literal["enum", "row", "column", "dense", ] | str
    grid_auto_rows: Literal["length, percentage", ] | str
    grid_column: Literal["identifier, integer, enum", "auto", "span", ] | str
    grid_column_end: Literal["identifier, integer, enum", "auto", "span", ] | str
    grid_column_gap: Literal["length", ] | str
    grid_column_start: Literal["identifier, integer, enum", "auto", "span", ] | str
    grid_gap: Literal["length", ] | str
    grid_row: Literal["identifier, integer, enum", "auto", "span", ] | str
    grid_row_end: Literal["identifier, integer, enum", "auto", "span", ] | str
    grid_row_gap: Literal["length", ] | str
    grid_row_start: Literal["identifier, integer, enum", "auto", "span", ] | str
    grid_template: Literal["identifier, length, percentage, string, enum", "none", "min-content", "max-content", "auto", "subgrid", "minmax()", "repeat()", ] | str
    grid_template_areas: Literal["string", ] | str
    grid_template_columns: Literal["identifier, length, percentage, enum", "none", "min-content", "max-content", "auto", "subgrid", "minmax()", "repeat()", ] | str
    grid_template_rows: Literal["identifier, length, percentage, string, enum", "none", "min-content", "max-content", "auto", "subgrid", "minmax()", "repeat()", ] | str
    hanging_punctuation: Literal["enum", "allow-end", "first", "force-end", "last", "none", ] | str
    height: Literal["length, percentage", ] | str
    hyphenate_character: Literal["string, enum", ] | str
    hyphenate_limit_chars: Literal["integer, enum", ] | str
    hyphenate_limit_last: Literal["enum", "none", "always", "column", "page", "spread", ] | str
    hyphenate_limit_lines: Literal["integer", ] | str
    hyphenate_limit_zone: Literal["percentage, length", ] | str
    hyphens: Literal["enum", "auto", "manual", "none", ] | str
    image_orientation: Literal["angle", ] | str
    image_rendering: Literal["enum", "auto", "crisp-edges", "-moz-crisp-edges", "optimizeQuality", "optimizeSpeed", "pixelated", ] | str
    image_resolution: Literal["resolution", ] | str
    ime_mode: Literal["enum", "active", "auto", "disabled", "inactive", "normal", ] | str
    initial_letter: Literal["number, integer, enum", ] | str
    initial_letter_align: Literal["enum", "alphabetic", "ideographic", "hebrew", "hanging", "border-box", ] | str
    initial_letter_wrap: Literal["length, percentage, enum", "none", "first", "all", "grid", ] | str
    inline_size: Literal["length, percentage", ] | str
    isolation: Literal["enum", "auto", "isolate", ] | str
    justify_content: Literal["enum", "center", "start", "end", "left", "right", "safe", "unsafe", "stretch", "space-evenly", "flex-end", "flex-start", "space-around", "space-between", "baseline", "first baseline", "last baseline", ] | str
    justify_items: Literal["enum", "auto", "normal", "end", "start", "flex-end", "flex-start", "self-end", "self-start", "center", "left", "right", "baseline", "first baseline", "last baseline", "stretch", "safe", "unsafe", "legacy", ] | str
    justify_self: Literal["enum", "auto", "normal", "end", "start", "flex-end", "flex-start", "self-end", "self-start", "center", "left", "right", "baseline", "first baseline", "last baseline", "stretch", "save", "unsave", ] | str
    kerning: Literal["length, enum", ] | str
    left: Literal["length, percentage", ] | str
    letter_spacing: Literal["length", ] | str
    lighting_color: Literal["color", ] | str
    line_break: Literal["enum", "auto", "loose", "normal", "strict", "anywhere", ] | str
    line_grid: Literal["enum", "match-parent", "create", ] | str
    line_height: Literal["number, length, percentage", ] | str
    line_snap: Literal["enum", "none", "baseline", "contain", ] | str
    list_style: Literal["image, enum, url", "armenian", "circle", "decimal", "decimal-leading-zero", "disc", "georgian", "hanging", "inside", "lower-alpha", "lower-greek", "lower-latin", "lower-roman", "none", "outside", "square", "symbols()", "upper-alpha", "upper-latin", "upper-roman", "url()", ] | str
    list_style_image: Literal["image", ] | str
    list_style_position: Literal["enum", "inside", "outside", ] | str
    list_style_type: Literal["enum, string", "arabic-indic", "armenian", "bengali", "cambodian", "circle", "cjk-decimal", "cjk-earthly-branch", "cjk-heavenly-stem", "decimal", "decimal-leading-zero", "devanagari", "disc", "disclosure-closed", "disclosure-open", "georgian", "gujarati", "gurmukhi", "hebrew", "hiragana", "hiragana-iroha", "kannada", "katakana", "katakana-iroha", "khmer", "lao", "lower-alpha", "lower-armenian", "lower-greek", "lower-latin", "lower-roman", "malayalam", "mongolian", "myanmar", "none", "oriya", "persian", "square", "tamil", "telugu", "thai", "tibetan", "symbols()", "upper-alpha", "upper-armenian", "upper-latin", "upper-roman", ] | str
    margin: Literal["length, percentage", ] | str
    margin_block_end: Literal["length, percentage", ] | str
    margin_block_start: Literal["length, percentage", ] | str
    margin_bottom: Literal["length, percentage", ] | str
    margin_inline_end: Literal["length, percentage", ] | str
    margin_inline_start: Literal["length, percentage", ] | str
    margin_left: Literal["length, percentage", ] | str
    margin_right: Literal["length, percentage", ] | str
    margin_top: Literal["length, percentage", ] | str
    marker: Literal["url", ] | str
    marker_end: Literal["url", ] | str
    marker_mid: Literal["url", ] | str
    marker_side: Literal["enum", "list-item", "list-container", ] | str
    marker_start: Literal["url", ] | str
    mask: Literal["url, image, length, percentage, position, repeat, geometry-box, enum", "none", "url()", "alpha", "auto", "luminance", "contain", "cover", "no-clip", "add", "exclude", "intersect", "subtract", ] | str
    mask_border: Literal["image, length, number, percentage, enum", "none", "fill", "auto", "repeat", "round", "space", "stretch", "alpha", "luminance", ] | str
    mask_border_mode: Literal["enum", "alpha", "luminance", ] | str
    mask_border_outset: Literal["length, number", ] | str
    mask_border_repeat: Literal["enum", "repeat", "round", "space", "stretch", ] | str
    mask_border_slice: Literal["number, percentage, enum", ] | str
    mask_border_source: Literal["image, enum", ] | str
    mask_border_width: Literal["length, percentage, enum", ] | str
    mask_clip: Literal["geometry-box, enum", ] | str
    mask_composite: Literal["enum", "add", "exclude", "intersect", "subtract", ] | str
    mask_image: Literal["url, image, enum", "none", "url()", ] | str
    mask_mode: Literal["url, image, enum", "alpha", "auto", "luminance", ] | str
    mask_origin: Literal["geometry-box, enum", ] | str
    mask_position: Literal["position, length, percentage", ] | str
    mask_repeat: Literal["repeat", ] | str
    mask_size: Literal["length, percentage, enum", "auto", "contain", "cover", ] | str
    mask_type: Literal["enum", "alpha", "luminance", ] | str
    max_block_size: Literal["length, percentage", ] | str
    max_height: Literal["length, percentage", ] | str
    max_inline_size: Literal["length, percentage", ] | str
    max_lines: Literal["integer, enum", ] | str
    max_width: Literal["length, percentage", ] | str
    max_zoom: Literal["number, percentage, enum", ] | str
    min_block_size: Literal["length, percentage", ] | str
    min_height: Literal["length, percentage", ] | str
    min_inline_size: Literal["length, percentage", ] | str
    min_width: Literal["length, percentage", ] | str
    min_zoom: Literal["number, percentage, enum", ] | str
    mix_blend_mode: Literal["enum", "normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "color-burn", "hard-light", "soft-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity", ] | str
    motion: Literal["url, length, percentage, angle, shape, geometry-box, enum", "none", "path()", "url()", "auto", "reverse", ] | str
    motion_offset: Literal["length, percentage", ] | str
    motion_path: Literal["url, shape, geometry-box, enum", "none", "path()", "url()", ] | str
    motion_rotation: Literal["angle", ] | str
    move_to: Literal["identifier", ] | str
    nav_down: Literal["enum, identifier, string", "auto", "current", "root", ] | str
    nav_index: Literal["number", ] | str
    nav_left: Literal["enum, identifier, string", "auto", "current", "root", ] | str
    nav_right: Literal["enum, identifier, string", "auto", "current", "root", ] | str
    nav_up: Literal["enum, identifier, string", "auto", "current", "root", ] | str
    negative: Literal["image, identifier, string", ] | str
    object_fit: Literal["enum", "contain", "cover", "fill", "none", "scale-down", ] | str
    object_position: Literal["position, length, percentage", ] | str
    offset_block_end: Literal["length, percentage", ] | str
    offset_block_start: Literal["length, percentage", ] | str
    offset_inline_end: Literal["length, percentage", ] | str
    offset_inline_start: Literal["length, percentage", ] | str
    opacity: Literal["number(0-1)", ] | str
    order: Literal["integer", ] | str
    orientation: Literal["enum", "auto", "landscape", "portrait", ] | str
    orphans: Literal["integer", ] | str
    outline: Literal["length, line-width, line-style, color, enum", "auto", "invert", ] | str
    outline_color: Literal["enum, color", ] | str
    outline_offset: Literal["length", ] | str
    outline_style: Literal["line-style, enum", ] | str
    outline_width: Literal["length, line-width", ] | str
    overflow: Literal["enum", "auto", "clip", "hidden", "-moz-hidden-unscrollable", "scroll", "visible", ] | str
    overflow_wrap: Literal["enum", "break-word", "normal", "anywhere", ] | str
    overflow_x: Literal["enum", "auto", "clip", "hidden", "scroll", "visible", ] | str
    overflow_y: Literal["enum", "auto", "clip", "hidden", "scroll", "visible", ] | str
    pad: Literal["integer, image, string, identifier", ] | str
    padding: Literal["length, percentage", ] | str
    padding_block_end: Literal["length, percentage", ] | str
    padding_block_start: Literal["length, percentage", ] | str
    padding_bottom: Literal["length, percentage", ] | str
    padding_inline_end: Literal["length, percentage", ] | str
    padding_inline_start: Literal["length, percentage", ] | str
    padding_left: Literal["length, percentage", ] | str
    padding_right: Literal["length, percentage", ] | str
    padding_top: Literal["length, percentage", ] | str
    page: Literal["identifier", ] | str
    page_break_after: Literal["enum", "always", "auto", "avoid", "left", "recto", "right", "verso", ] | str
    page_break_before: Literal["enum", "always", "auto", "avoid", "left", "right", ] | str
    page_break_inside: Literal["enum", "auto", "avoid", ] | str
    page_policy: Literal["enum", "first", "last", "start", ] | str
    paint_order: Literal["enum", "fill", "markers", "normal", "stroke", ] | str
    pause: Literal["time, enum", "medium", "none", "strong", "weak", "x-strong", "x-weak", ] | str
    pause_after: Literal["time", ] | str
    pause_before: Literal["time", ] | str
    perspective: Literal["length, enum", ] | str
    perspective_origin: Literal["position, percentage, length", ] | str
    pointer_events: Literal["enum", "all", "fill", "none", "painted", "stroke", "visible", "visibleFill", "visiblePainted", "visibleStroke", ] | str
    position: Literal["enum", "absolute", "center", "fixed", "-ms-page", "page", "relative", "static", "sticky", "-webkit-sticky", ] | str
    prefix: Literal["image, string, identifier", ] | str
    quotes: Literal["string", ] | str
    r: Literal["length, percentage", ] | str
    range: Literal["integer, enum", "auto", "infinite", ] | str
    region_fragment: Literal["enum", "auto", "break", ] | str
    resize: Literal["enum", "both", "block", "horizontal", "inline", "none", "vertical", ] | str
    rest: Literal["time", ] | str
    rest_after: Literal["time", ] | str
    rest_before: Literal["time", ] | str
    right: Literal["length, percentage", ] | str
    rotation: Literal["angle", ] | str
    rotation_point: Literal["position, percentage, length", ] | str
    ruby_align: Literal["enum", "auto", "center", "distribute-letter", "distribute-space", "left", "line-edge", "right", "start", "space-between", "space-around", ] | str
    ruby_overhang: Literal["enum", "auto", "end", "none", "start", ] | str
    ruby_position: Literal["enum", "after", "before", "inline", "right", ] | str
    ruby_span: Literal["enum", "attr(x)", "none", ] | str
    rx: Literal["length, percentage", ] | str
    ry: Literal["length, percentage", ] | str
    scroll_behavior: Literal["enum", "auto", "smooth", ] | str
    scroll_snap_coordinate: Literal["position, length, percentage, enum", "none", "border-box", "margin-box", ] | str
    scroll_snap_destination: Literal["position, length, percentage", ] | str
    scroll_snap_points_x: Literal["enum", "none", "repeat()", ] | str
    scroll_snap_points_y: Literal["enum", "none", "repeat()", ] | str
    scroll_snap_type: Literal["enum", "none", "mandatory", "proximity", ] | str
    scrollbar_3dlight_color: Literal["color", ] | str
    scrollbar_arrow_color: Literal["color", ] | str
    scrollbar_base_color: Literal["color", ] | str
    scrollbar_darkshadow_color: Literal["color", ] | str
    scrollbar_face_color: Literal["color", ] | str
    scrollbar_highlight_color: Literal["color", ] | str
    scrollbar_shadow_color: Literal["color", ] | str
    scrollbar_track_color: Literal["color", ] | str
    shape_image_threshold: Literal["number", ] | str
    shape_inside: Literal["image, shape, box, enum", "auto", "display", "margin-box", "outside-shape", "url()", ] | str
    shape_margin: Literal["url, length, percentage", ] | str
    shape_outside: Literal["image, box, shape, enum", "margin-box", "none", ] | str
    shape_padding: Literal["length", ] | str
    shape_rendering: Literal["enum", "auto", "crispEdges", "geometricPrecision", "optimizeSpeed", ] | str
    size: Literal["length", ] | str
    speak: Literal["enum", "auto", "none", "normal", ] | str
    speak_as: Literal["enum", "digits", "literal-punctuation", "no-punctuation", "normal", "spell-out", ] | str
    src: Literal["enum, url, identifier", "url()", "format()", "local()", ] | str
    stop_color: Literal["color", ] | str
    stop_opacity: Literal["number(0-1)", ] | str
    stroke: Literal["color, enum, url", "child", "child()", "context-fill", "context-stroke", "url()", "none", ] | str
    stroke_dasharray: Literal["length, percentage, number, enum", ] | str
    stroke_dashoffset: Literal["percentage, length", ] | str
    stroke_linecap: Literal["enum", "butt", "round", "square", ] | str
    stroke_linejoin: Literal["enum", "arcs", "bevel", "miter", "miter-clip", "round", ] | str
    stroke_miterlimit: Literal["number", ] | str
    stroke_opacity: Literal["number(0-1)", ] | str
    stroke_width: Literal["percentage, length", ] | str
    suffix: Literal["image, string, identifier", ] | str
    symbols: Literal["image, string, identifier", ] | str
    system: Literal["enum, integer", "additive", "alphabetic", "cyclic", "extends", "fixed", "numeric", "symbolic", ] | str
    tab_size: Literal["integer, length", ] | str
    table_layout: Literal["enum", "auto", "fixed", ] | str
    text_align: Literal["string", ] | str
    text_align_last: Literal["enum", "auto", "center", "end", "justify", "left", "right", "start", ] | str
    text_anchor: Literal["enum", "end", "middle", "start", ] | str
    text_combine_upright: Literal["enum, integer", "all", "digits", "none", ] | str
    text_decoration: Literal["enum, color", "dashed", "dotted", "double", "line-through", "none", "overline", "solid", "underline", "wavy", ] | str
    text_decoration_color: Literal["color", ] | str
    text_decoration_line: Literal["enum", "line-through", "none", "overline", "underline", ] | str
    text_decoration_skip: Literal["enum", "box-decoration", "ink", "none", "objects", "spaces", ] | str
    text_decoration_style: Literal["enum", "dashed", "dotted", "double", "none", "solid", "wavy", ] | str
    text_emphasis: Literal["color, string", ] | str
    text_emphasis_color: Literal["color", ] | str
    text_emphasis_position: Literal["enum", "over", "under", "left", "right", ] | str
    text_emphasis_style: Literal["string", ] | str
    text_indent: Literal["percentage, length", ] | str
    text_justify: Literal["enum", "auto", "distribute", "distribute-all-lines", "inter-character", "inter-cluster", "inter-ideograph", "inter-word", "kashida", "newspaper", "none", ] | str
    text_orientation: Literal["enum", "mixed", "sideways", "sideways-left", "sideways-right", "upright", "use-glyph-orientation", ] | str
    text_overflow: Literal["enum, string", "clip", "ellipsis", ] | str
    text_rendering: Literal["enum", "auto", "geometricPrecision", "optimizeLegibility", "optimizeSpeed", ] | str
    text_shadow: Literal["length, color", ] | str
    text_size_adjust: Literal["enum, percentage", "auto", "none", ] | str
    text_space_collapse: Literal["enum", "collapse", "discard", "preserve", "preserve-auto", "preserve-trim", "preserve-breaks", "preserve-spaces", ] | str
    text_space_trim: Literal["enum", "none", "trim-inner", "discard-before", "discard-after", ] | str
    text_spacing: Literal["enum", "normal", "none", "trim-start", "space-start", "trim-end", "space-end", "allow-end", "trim-adjacent", "space-adjacent", "no-compress", "ideograph-alpha", "ideograph-numeric", "punctuation", ] | str
    text_transform: Literal["enum", "capitalize", "full-width", "lowercase", "none", "uppercase", ] | str
    text_underline_position: Literal["enum", "above", "auto", "below", "left", "right", "under", ] | str
    text_wrap: Literal["enum", "balance", "normal", "nowrap", ] | str
    top: Literal["length, percentage", ] | str
    touch_action: Literal["enum", "auto", "cross-slide-x", "cross-slide-y", "double-tap-zoom", "manipulation", "none", "pan-x", "pan-y", "pinch-zoom", ] | str
    transform: Literal["enum", "matrix()", "matrix3d()", "none", "perspective()", "rotate()", "rotate3d()", "rotateX('angle')", "rotateY('angle')", "rotateZ('angle')", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skew()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()", ] | str
    transform_box: Literal["enum", "border-box", "fill-box", "view-box", ] | str
    transform_origin: Literal["position, length, percentage", ] | str
    transform_style: Literal["enum", "flat", "preserve-3d", ] | str
    transition: Literal["time, property, timing-function, enum", "all", "none", ] | str
    transition_delay: Literal["time", ] | str
    transition_duration: Literal["time", ] | str
    transition_property: Literal["property", ] | str
    transition_timing_function: Literal["timing-function", ] | str
    unicode_bidi: Literal["enum", "bidi-override", "embed", "isolate", "isolate-override", "normal", "plaintext", ] | str
    unicode_range: Literal["unicode-range", ] | str
    user_select: Literal["enum", "all", "auto", "contain", "none", "text", ] | str
    user_zoom: Literal["enum", "fixed", "zoom", ] | str
    vector_effect: Literal["enum", "fixed-position", "none", "non-rotation", "non-scaling-size", "non-scaling-stroke", "screen", "viewport", ] | str
    vertical_align: Literal["percentage, length", ] | str
    visibility: Literal["enum", "collapse", "hidden", "visible", ] | str
    voice_balance: Literal["number(-100-100)", ] | str
    voice_duration: Literal["time", ] | str
    voice_family: Literal["number, string, identifier", ] | str
    voice_pitch: Literal["percentage, number, frequency, semitones", ] | str
    voice_range: Literal["percentage, number, frequency, semitones", ] | str
    voice_rate: Literal["percentage", ] | str
    voice_stress: Literal["enum", "moderate", "none", "normal", "reduced", "strong", ] | str
    voice_volume: Literal["volume, enum", "loud", "medium", "silent", "soft", "x-loud", "x-soft", ] | str
    widows: Literal["integer", ] | str
    width: Literal["length, percentage", ] | str
    will_change: Literal["enum, identifier", "auto", "contents", "scroll-position", ] | str
    word_break: Literal["enum", "break-all", "keep-all", "normal", ] | str
    word_spacing: Literal["length, percentage", ] | str
    word_wrap: Literal["enum", "break-word", "normal", ] | str
    wrap_after: Literal["enum", "auto", "avoid", "avoid-line", "avoid-flex", "line", "flex", ] | str
    wrap_before: Literal["enum", "auto", "avoid", "avoid-line", "avoid-flex", "line", "flex", ] | str
    wrap_flow: Literal["enum", "auto", "both", "clear", "end", "maximum", "minimum", "start", ] | str
    wrap_inside: Literal["enum", "auto", "avoid", ] | str
    wrap_through: Literal["enum", "none", "wrap", ] | str
    writing_mode: Literal["enum", "horizontal-tb", "sideways-lr", "sideways-rl", "vertical-lr", "vertical-rl", ] | str
    x: Literal["length, percentage", ] | str
    y: Literal["length, percentage", ] | str
    z_index: Literal["integer", ] | str
    zoom: Literal["enum, integer, number, percentage", ] | str
